name: dollar
description: Write side effects in sync functions.
version: 0.0.2
homepage: https://github.com/pinyin/dollar
author: Bo Bao <bob432091@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  collection: ^1.14.11

dev_dependencies:
  test: ^1.0.0
