name: dollar
description: Use $tateful functions everywhere.
version: 0.1.1
homepage: https://github.com/pinyin/dollar
author: Bo Bao <bob432091@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
